apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T04:22:30Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1961"
  uid: 0d0d3960-8f7e-4869-b4f2-9eb54d4cd4a9
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.111.22.80
  clusterIPs:
  - 10.111.22.80
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32092
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
